export const PRIMITIVE_PART = 0x1;
export const COMPOSED_PART = 0x2;
export const SELECT_PART = 0x4;
export const UPDATE_PART = 0x8;

export const STATEFUL_PART = PRIMITIVE_PART | COMPOSED_PART;
export const SELECTABLE_PART = STATEFUL_PART | SELECT_PART;

export const READ_WRITE_PART = PRIMITIVE_PART | COMPOSED_PART;
export const READ_ONLY_PART = SELECT_PART;
export const WRITE_ONLY_PART = UPDATE_PART;

export const PART = READ_WRITE_PART | READ_ONLY_PART | READ_WRITE_PART;
